// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyProj.Entities;
using PharmacyProj.Services;

#nullable disable

namespace PharmacyProj.Entities.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pharmacy_Proj.Entities.Entities.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FilledPrescriptions")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pharmacy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "Dallas",
                            CreatedBy = "ben@test.com",
                            CreatedDate = new DateTime(2024, 1, 9, 17, 23, 10, 492, DateTimeKind.Local).AddTicks(743),
                            FilledPrescriptions = 50,
                            Name = "Walgreens",
                            PharmacyId = 1,
                            State = "TX",
                            Zip = "12345"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St",
                            City = "Frisco",
                            CreatedBy = "ben@test.com",
                            CreatedDate = new DateTime(2024, 1, 9, 17, 23, 10, 492, DateTimeKind.Local).AddTicks(783),
                            FilledPrescriptions = 75,
                            Name = "CVS",
                            PharmacyId = 2,
                            State = "TX",
                            Zip = "23456"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St",
                            City = "Richardson",
                            CreatedBy = "ben@test.com",
                            CreatedDate = new DateTime(2024, 1, 9, 17, 23, 10, 492, DateTimeKind.Local).AddTicks(785),
                            FilledPrescriptions = 100,
                            Name = "Walmart Pharmacy",
                            PharmacyId = 3,
                            State = "TX",
                            Zip = "34567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Elm St",
                            City = "McKinney",
                            CreatedBy = "ben@test.com",
                            CreatedDate = new DateTime(2024, 1, 9, 17, 23, 10, 492, DateTimeKind.Local).AddTicks(788),
                            FilledPrescriptions = 125,
                            Name = "Kroger Pharmacy",
                            PharmacyId = 4,
                            State = "TX",
                            Zip = "45678"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Birch St",
                            City = "Frisco",
                            CreatedBy = "ben@test.com",
                            CreatedDate = new DateTime(2024, 1, 9, 17, 23, 10, 492, DateTimeKind.Local).AddTicks(790),
                            FilledPrescriptions = 150,
                            Name = "HEB Pharmacy",
                            PharmacyId = 5,
                            State = "TX",
                            Zip = "56789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
